# Generated by Django 2.1.1 on 2018-09-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bogota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('correo', models.EmailField(max_length=254)),
                ('celular', models.BigIntegerField()),
                ('terminos', models.BooleanField()),
                ('politica', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Medellin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('correo', models.EmailField(max_length=254)),
                ('celular', models.BigIntegerField()),
                ('terminos', models.BooleanField()),
                ('politica', models.BooleanField()),
            ],
        ),
    ]
