# Generated by Django 2.1.1 on 2018-09-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('celular', models.BigIntegerField()),
                ('ciudad', models.CharField(choices=[('Bg', 'Bogotá'), ('Md', 'Medellín')], default='Bg', max_length=2)),
                ('terminos', models.BooleanField()),
                ('politica', models.BooleanField()),
                ('codigo', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
